name: Release package to registry.npmjs.org

on:
  push:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "ci-bot@ssi.com.vn"
      - run: git config --global user.name "SSI"
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'fc-trading.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig /*.github/*'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Install semantic-release extra plugins
        run: npm install --no-save @semantic-release/changelog @semantic-release/git
        
      - name: Semantic Release
        run: npx semantic-release